Script started on 2020-11-01 01:57:06-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="168" LINES="14"]
]0;dxgriego@Parallels: ~/cse113/lab7[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab7[00m$ make dynamic 
clang -O2 -c str.c
clang -O2 dynamic.c str.o -o dynamic 
]0;dxgriego@Parallels: ~/cse113/lab7[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab7[00m$ valgrie[Knd[K[Knd[K[K[K[K[K[K[K[Kvalgrind --leak-check=yes ./duy[K[Kynamic 
==21015== Memcheck, a memory error detector
==21015== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==21015== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==21015== Command: ./dynamic
==21015== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==21015== 
==21015== HEAP SUMMARY:
==21015==     in use at exit: 0 bytes in 0 blocks
==21015==   total heap usage: 2 allocs, 2 frees, 1,067 bytes allocated
==21015== 
==21015== All heap blocks were freed -- no leaks are possible
==21015== 
==21015== For lists of detected and suppressed errors, rerun with: -s
==21015== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;dxgriego@Parallels: ~/cse113/lab7[01;32mdxgriego@Parallels[00m:[01;34m~/cse113/lab7[00m$ exit
exit

Script done on 2020-11-01 01:58:09-06:00 [COMMAND_EXIT_CODE="0"]
